# Host to use for canonical URL generation (without trailing slash)
host: registers-docs.cloudapps.digital

# Header-related options
show_govuk_logo: false
service_name: Registers
service_link: https://registers.cloudapps.digital/
phase: Beta

# Links to show on right-hand-side of header
header_links:
  Using registers: https://registers.cloudapps.digital/using-registers.html
  Register status: https://registers.cloudapps.digital/registers
  Support: https://registers.cloudapps.digital/support.html
  Documentation: /

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:
